[project]
name = "fab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "numpy>=2.3.4",
    "requests>=2.32.5",
    "sentence-transformers>=5.1.2",
    "transformers>=4.40.0",
]
